# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voiceassistant
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

# JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # OpenAI
openai:
  api:
    key: ${OPENAI_API_KEY:your-api-key-here}
  
  # Server
server:
  port: 8080
  
  # CORS
  web:
    cors:
      allowed-origins: *
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: *