# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/voiceassistant
    username: ${POSTGRES_USER:azizzakiryarov}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# OpenAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

  # Server
server:
  port: 8081

google:
  calendar:
    client-id: ${GOOGLE_CALENDAR_CLIENT_ID}
    client-secret: ${GOOGLE_CALENDAR_CLIENT_SECRET}
    application-name: voice-assistent-client
    tokens-directory: /app/tokens

# CORS
web:
  cors:
    allowed-origins: '*'
    allowed-methods: 'GET,POST,PUT,DELETE'
    allowed-headers: 'Authorization,Content-Type,X-Requested-With'