# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voiceassistant
    username: ${POSTGRES_USER:azizzakiryarov}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# OpenAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

  # Server
server:
  port: 8081

google:
  # Sökväg till din service account nyckel-fil
  service-account:
    key-file: classpath:voice-assistent-451109-4acde9fca270.json
  # Kalender-ID: använd primary för användarens egen kalender
  # Eller använd kalender-ID för en delad kalender
  calendar:
    calendar-id: primary

# CORS
web:
  cors:
    allowed-origins: 'http://localhost:5173/'
    allowed-methods: 'GET,POST,PUT,DELETE'
    allowed-headers: 'Authorization,Content-Type,X-Requested-With'


