spring:
  profiles:
    active: utv
  datasource:
    url: jdbc:postgresql://postgres:5432/voiceassistant
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver